version: "3.8"
services:

  namegame-mysql:
    image: mysql:8.0
    container_name: ${MYSQL_DATABASE}
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    # Uncomment to persist data in a volume
    volumes:
      - ./mysql_data:/var/lib/mysql
